import sys
sys.path.append("/home/luca/Documents/allpix/ROOT/root_install/lib") #replace with directory of your folder lib
import ROOT
from ROOT import TFile, gDirectory, gSystem, TClass
import pandas as pd
import numpy as np
import os
import argparse
import os.path as path
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
from scipy.stats import norm
from scipy.optimize import curve_fit
import pickle
from tqdm import tqdm
from datetime import datetime


def check_water_before_detector(group):
    """ This is a function to assign a new code column to the dataframe. In this case the column brings true information about wether or not the
    interactions come from a primary or scattered photon:

    0: the photon is scattered in the object
    1: the photon is primary
    2: the photon is primary but after the detector it interacts with water and then re-interacts with a detector

    input: the event_id subgroup from the dataset
    output: the group is returned with added column
    """

    # Find index of first occurrences of "water" and "detector" using partial match
    detector_mask = group['volume_origin'].str.contains('sensor', case=False, na=False)
    water_mask = group['volume_origin'].str.contains('water', case=False, na=False)

    detector_indices = group.index[detector_mask].tolist()
    water_indices = group.index[water_mask].tolist()

    # Default value for Photon_primary
    photon_primary = 1  # Default: detector appears before water or only detector is present

    if water_indices:  # If there is at least one "water"
        first_water_idx = min(water_indices)

        # Case 1: Water appears before any detector -> Assign 0
        if detector_indices and first_water_idx < min(detector_indices):
            photon_primary = 0
        # Case 2: Detector appears first but another detector is present after water -> Assign 2
        elif any(idx > first_water_idx for idx in detector_indices):
            photon_primary = 2

    # Assign Photon_primary to all rows in the group
    group['photon_primary'] = photon_primary
    return group

# these below are the only things one need to change all the rest is parametrized
### 0----------------------------------------0000000000000000000--------------------------------------------0 ###


root_file_name = "/home/luca/Desktop/PhD/allpix2/Simple_detector_photon_simulation/output/full_detector_bulk_140kev_5x20x20cm.root"

# These next 3 lines are important as they add a world global time to the local time stamps generated by allpix, which restart to zero for each new photon generated.
source_activity = 500 #in MBq

#this needs to be changed accordingly to how many events you want to read.
N_events_to_read = 1000000

water_radius = 0
starting_iev = 0
### 0----------------------------------------0000000000000000000--------------------------------------------0 ###
cum_sum_time = 0
lambda_source = source_activity * 10e6 #emissions per second

# the columns in the dataframe, advisable not to change them unless you know what you are doing
column_names_finalPD = ["event_ID", "init_x", "init_y", "init_z", "init_kin","time", "E_dep", "photon_ID","process_name","volume_interaction","photon_primary"]
column_names_smallPD = ["init_x", "init_y", "init_z", "time","init_kin", "process_name", "particle_ID","track_ID","parent_ID","volume_origin"]

lib_path = "/home/luca/Documents/allpix/allpix-squared/lib/libAllpixObjects.so"

# here are just some checks
if lib_path is not None:  # Try to find Allpix Library
    lib_file_name = (str(lib_path))
    if (not os.path.isfile(lib_file_name)):
        print("WARNING: ", lib_file_name, " does not exist, exiting")
        exit(1)
elif os.path.isfile(path.abspath(
        path.join(__file__, "..", "..", "opt", "allpix-squared", "lib", "libAllpixObjects.so"))):  # For native installs
    lib_file_name = path.abspath(path.join(__file__, "..", "..", "opt", "allpix-squared", "lib", "libAllpixObjects.so"))

elif os.path.isfile(path.join(path.sep, "opt", "allpix-squared", "lib", "libAllpixObjects.so")):  # For Docker installs
    lib_file_name = path.join(path.sep, "opt", "allpix-squared", "lib", "libAllpixObjects.so")

else:
    print("WARNING: No Allpix Objects Library found, exiting")
    exit(1)

if (not os.path.isfile(lib_file_name)):
    print("WARNING: no allpix library found, exiting (Use -l to manually set location of libraries)")
    exit(1)
if (not os.path.isfile(root_file_name)):
    print("WARNING: " + root_file_name + " does not exist, exiting")
    exit(1)

gSystem.Load(lib_file_name)
rootfile = ROOT.TFile(root_file_name)
gDirectory.ls()

### 0----------------------------------------0000000000000000000--------------------------------------------0 ###
#to be changed in case one wants to modify the objects read
McTrack = rootfile.Get('MCTrack')
total_events=McTrack.GetEntries()
if total_events < N_events_to_read+starting_iev:
    print("Number of events to be read exceedes the total number of events simulated, exiting")
    exit(1)
if N_events_to_read > 1000000:
    user_input = input("Watch out, reading more than 1000000 events might require a lot of memory, do you want to continue? (Y/N): ")
    if user_input.lower() in ["Y","y"]:
        print("Continuing...")
    else:
        print("Exiting...")
        exit(1)

    if user_input.lower() in ["Y","y"]:
        print("Continuing...")
    else:
        print("Exiting...")
        exit(1)
print("Preallocating memory for dataframe")
smallPD_len = 200 #this is just to be bigger than the number of rows an event can have
finalPD_len = 10*N_events_to_read #this is set to contain all events interacting with a detector


df_final = pd.DataFrame(columns=column_names_finalPD, index=range(finalPD_len))
df_init_en = pd.DataFrame(columns=column_names_smallPD, index=range(finalPD_len))

events_not_interacting_detector=0
eBrem_skip = 0


#just used to reference where we are in the two dataframes. I tried some things and this seemed like the fastest way
smallPD_row_counter = 0
finalPD_row_counter = 0

for j in tqdm(range(N_events_to_read), desc="Processing", unit="step", leave=True, miniters=5000): #int(McTrack.GetEntries()/2)
    iev = j + starting_iev
    # we initialize the small dataframe, used to read directly from root and process to keep only the interactions and then being merged
    # into the final one. this is to speed up the process compared to manipulate each time a very long dataframe
    df_small = pd.DataFrame(columns=column_names_smallPD, index=range(smallPD_len))
    McTrack.GetEntry(iev)
    McTrack_branch = McTrack.GetBranch("global")

    if (not McTrack_branch):
        Warning("WARNING: cannot find McTrack branch in the TTree,  exiting")
        exit(1)

    br_mc_track = getattr(McTrack, McTrack_branch.GetName())

    time_to_add = np.random.exponential(1 / lambda_source) * 10e9 # in ns
    cum_sum_time += time_to_add


    for mc_track in br_mc_track:

        # here we record all the important information that we will use to characterize the interaction and debug if needed

        df_small.at[smallPD_row_counter, 'init_x'] = mc_track.getStartPoint().x()
        df_small.at[smallPD_row_counter,'init_y'] = mc_track.getStartPoint().y()
        df_small.at[smallPD_row_counter,'init_z'] = mc_track.getStartPoint().z()
        df_small.at[smallPD_row_counter, 'time'] = mc_track.getGlobalStartTime() + cum_sum_time
        df_small.at[smallPD_row_counter,'init_kin'] = mc_track.getKineticEnergyInitial()
        df_small.at[smallPD_row_counter, 'process_name']= mc_track.getCreationProcessName()
        df_small.at[smallPD_row_counter, 'particle_ID']= mc_track.getParticleID()
        df_small.at[smallPD_row_counter, 'parent_ID'] = hex(ROOT.addressof(mc_track.getParent()))
        df_small.at[smallPD_row_counter, 'track_ID'] = hex(ROOT.addressof(mc_track))
        df_small.at[smallPD_row_counter, 'volume_origin'] = mc_track.getOriginatingVolumeName()

        smallPD_row_counter += 1



    df_small = df_small.sort_values(by="time").reset_index(drop=True)
    primary_photon_ID = df_small['track_ID'].iloc[0]
    df_init_en.iloc[iev] = df_small.iloc[0].values
    mask = df_small['particle_ID'] == 11
    if mask.any():
        first_index = mask.idxmax()  # Get the index of the first occurrence
        df_small = df_small.loc[first_index:].reset_index(drop=True)
    else:
        events_not_interacting_detector += 1
        smallPD_row_counter = 0
        continue


    #for now, we skip fluorescence and bremstrallung containing events, this can be changed but it would require
    #to change the algorithm that follows
    #if (df_small['particle_ID'] == 22).any():
    #    smallPD_row_counter = 0
    #    eBrem_skip +=1
    #    continue

    df_small = df_small.groupby('parent_ID', group_keys=False)[["init_x", "init_y", "init_z", "time","init_kin", "process_name", "particle_ID","track_ID","parent_ID","volume_origin"]].apply(check_water_before_detector)
    #TODO: fix here the is primary check since for fluorescent photons it will say yes but it is not if it originated from a non primary event
    df_small[['init_x', 'init_y', 'init_z']] = df_small[
        ['init_x', 'init_y', 'init_z']].apply(pd.to_numeric, errors='coerce')
    df_small = df_small[np.sqrt(df_small['init_y'] ** 2 + df_small['init_z'] ** 2) >= water_radius]
    if len(df_small)==0:
        events_not_interacting_detector +=1
        smallPD_row_counter = 0
        continue
    mask = df_small['particle_ID'] == 11
    df_small = df_small[mask].reset_index(drop=True)
    df_small = df_small.sort_values(by="time")
    if len(df_small) == 0:
        events_not_interacting_detector += 1
        smallPD_row_counter = 0
        continue

    df_small.loc[df_small['parent_ID'] != primary_photon_ID, 'process_name'] = 'compt'
    edep_sum = df_small['init_kin'].iloc[0] #summing all the deposited energy from different electrons in the same interaction
    current_int_pos = [df_small['init_x'].iloc[0], df_small['init_y'].iloc[0], df_small['init_z'].iloc[0]]
    current_int_time = df_small['time'].iloc[0]
    current_volume_int = df_small['volume_origin'].iloc[0]
    current_process_int = df_small['process_name'].iloc[0]
    current_parent_ID = df_small['parent_ID'].iloc[0]
    current_photon_primary = df_small['photon_primary'].iloc[0]
    current_init_kin = df_small['init_kin'].iloc[0]

#this next check is to avoid reading a ionization interaction taking place in a detector that originates from an electron
#created by a photon interaction in the phantom very close to the detector face.
    if current_process_int == 'eIoni':

        smallPD_row_counter = 0
        continue


    for j in range(1,len(df_small),1):


        if df_small['process_name'].iloc[j] == 'eIoni' :
             #if we have an electron that creates by ionization another electron we simplify skip since we are looking at the initial deposited energies

             continue

        point1 = np.array([df_small['init_x'].iloc[j], df_small['init_y'].iloc[j], df_small['init_z'].iloc[j]])
        point2 = np.array(current_int_pos)
        if np.linalg.norm(point1 - point2) < 0.05:
            #if the electron track we are looking at started close enough to the previous one we sum the energies togheter as they correspond to one single interaction
            #then we go to the next interaction
            edep_sum += df_small['init_kin'].iloc[j]





        else:
            #otherwise we save all the info on the interaction on the current point and we reset to move on and check on the next interaction

            df_final.at[finalPD_row_counter, 'event_ID'] = iev
            df_final.at[finalPD_row_counter, 'E_dep'] = edep_sum
            edep_sum = df_small['init_kin'].iloc[j]
            df_final.at[finalPD_row_counter, 'init_kin'] = current_init_kin
            df_final.at[finalPD_row_counter, 'init_x'] = current_int_pos[0]
            df_final.at[finalPD_row_counter, 'init_y'] = current_int_pos[1]
            df_final.at[finalPD_row_counter, 'init_z'] = current_int_pos[2]
            df_final.at[finalPD_row_counter, 'time'] = current_int_time
            df_final.at[finalPD_row_counter, 'volume_interaction'] = current_volume_int
            df_final.at[finalPD_row_counter, 'process_name'] = current_process_int
            df_final.at[finalPD_row_counter, 'photon_primary'] = current_photon_primary
            df_final.at[finalPD_row_counter, 'photon_ID'] = current_parent_ID
            current_photon_primary = df_small['photon_primary'].iloc[j]
            #df_final.at[finalPD_row_counter, 'init_kin_event'] = initial_kin_event
            current_int_pos = [df_small['init_x'].iloc[j], df_small['init_y'].iloc[j],
                               df_small['init_z'].iloc[j]]  # the element in 0 will always be the primary photon
            current_int_time = df_small['time'].iloc[j]
            current_volume_int = df_small['volume_origin'].iloc[j]
            current_process_int = df_small['process_name'].iloc[j]
            current_parent_ID = df_small['parent_ID'].iloc[j]
            current_init_kin = df_small['init_kin'].iloc[j]
            finalPD_row_counter += 1

    df_final.at[finalPD_row_counter, 'photon_primary'] = current_photon_primary
    df_final.at[finalPD_row_counter, 'event_ID'] = iev
    df_final.at[finalPD_row_counter, 'E_dep'] = edep_sum
    df_final.at[finalPD_row_counter, 'init_kin'] = current_init_kin
    df_final.at[finalPD_row_counter, 'init_x'] = current_int_pos[0]
    df_final.at[finalPD_row_counter, 'init_y'] = current_int_pos[1]
    df_final.at[finalPD_row_counter, 'init_z'] = current_int_pos[2]
    df_final.at[finalPD_row_counter, 'time'] = current_int_time
    df_final.at[finalPD_row_counter, 'volume_interaction'] = current_volume_int
    df_final.at[finalPD_row_counter, 'process_name'] = current_process_int
    df_final.at[finalPD_row_counter, 'photon_ID'] = current_parent_ID
    #df_final.at[finalPD_row_counter, 'init_kin_event'] = initial_kin_event

    finalPD_row_counter += 1
    smallPD_row_counter = 0

now= datetime.now()
curr_time= now.strftime("_%H:%M:%S")
df_final = df_final.dropna(how = 'all')
print('Total number of events read',N_events_to_read)
print('Events non interacting with the detector:', events_not_interacting_detector)
print('eBrem and fluorescent skipped counts:', eBrem_skip)
file_name = os.path.basename(root_file_name)
file_name = os.path.splitext(file_name)[0]
source_activity = str(source_activity)
df_init_en = df_init_en.dropna(how = 'all')
file_name_df = file_name +  source_activity + '_MBq'+ '_no_noise_pd_radii.pkl'
df_final.to_pickle(file_name_df)
file_name_df = file_name +  source_activity + '_MBq'+'_init_en'+ '_no_noise_pd_radii.pkl'
df_init_en.to_pickle(file_name_df)